package com.zavanton.yoump3.core.eventBus

enum class Event {

    INTENT_ACTION_URL,
    DOWNLOAD_URL,

    DOWNLOAD_STARTED,
    DOWNLOAD_PROGRESS,
    DOWNLOAD_SUCCESS,
    DOWNLOAD_ERROR,

    CONVERSION_STARTED,
    CONVERSION_PROGRESS,
    CONVERSION_SUCCESS,
    CONVERSION_ERROR,

}